
archive:
  root: ../archive

database:
  path: ../archive/data/
  filename: sermons.db

export:
  html_index: index.html

paths:
  manuscripts: files/manuscripts
  recordings:  files/recordings
  resources: files/resources

