# config.yaml - configurations for sermon

user: Oskar Fornander

root: ~/Oskar/predikan/archive  # Absolute path to sermon archive. See README.md for file structure.

database: sermon.db  # SQLite database file

paths:
  database: data
  backup: data/backup
  manuscripts: files/manuscripts
  recordings: files/recordings
  resources: files/resources
  html: html

apps:
  pdf: Preview
  audio: QuickTime Player
  video: QuickTime Player
  browser: Safari



