
archive:
  root: ../archive

database:
  path: ../archive/data/
  filename: sermons.db

export:
  html_index: index.html

files:
  manuscripts: manuscripts
  recordings: recordings
  resources: resources

paths:
  manuscripts: ../archive/files/manuscripts
  recordings:  ../archive/files/recordings
  resources: ../archive/files/resources

